## YAML Template.
---
version: "3.9"
services:
  db:
    image: mysql:8
    container_name: dms-db
    environment:
      MYSQL_DATABASE: dms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dms
      MYSQL_PASSWORD: dms
    ports: ["3306:3306"]
    volumes: ["db_data:/var/lib/mysql"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    ports: ["8081:8080"]   # DB UI at http://localhost:8081
volumes:
  db_data:
