## YAML Template.
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dms
    username: dms
    password: dms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
